language: ruby
rvm:
  - 2.1.6
  - 2.2.2
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - psql -c 'create database your-db-name' -U postgres